### PR TITLE
Also allow connections to the board via serial-over-WebUSB

### PR DESCRIPTION
**Pull request by joshlory**
Use the https://github.com/webusb/arduino library to add support for WebUSB serial connections.

This change is only for the Express board. I've verified a similar change for the Classic board. If the code looks good, I'll open that PR next!

### CODE REVIEW

**Comment by joshlory** [comment]
Not sure the best way to import libraries, but for my own reference here's how I got it working:

1. Download https://github.com/webusb/arduino/tree/gh-pages/library/WebUSB to `~/Documents/Arduino/libraries` on OS X.

image

2. The library then shows up under Sketch -> Include Library.

image

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
thanks for the patience, summer time almost over :)

**Comment by ladyada** [comment]
i cant replicate this being connectable in chrome/webusb. please send over a UF2 of what you have to try and narrow down the failure

**Comment by ladyada** [comment]
[tinyusb firmata.zip](https://github.com/adafruit/CircuitPlaygroundFirmata/files/3557408/tinyusb.firmata.zip)

here's my version using tinyusb for webusb support - it should work with both serial and webusb

**Pull request merged**
